# Generated by Django 4.2.1 on 2023-06-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marklist',
            name='total',
        ),
    ]
